#! /bin/bash


SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
#echo $SCRIPTPATH


if ! diff "$1" "$2" ; then
	$SCRIPTPATH/"$3" "$1" "${@:4}"
fi
