#! /bin/bash

SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
#echo $SCRIPTPATH

file=$1


if [ -f "$file" ] ; then
	oldIFS=$IFS
	IFS=$'\n' #field separator -> for loop

	for line in $(cat $file)
	do
		$SCRIPTPATH/"$2" "$line" "${@:3}"
	done

fi
IFS=$oldIFS
