#!/bin/bash

SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
#echo $SCRIPTPATH
n=254
if [ $2 ]; then
n=$2
fi

for a in `seq 1 $n`; do
	(
		ok=1
		ping -c 1 ${1%.*}.$a > /dev/null || ok=0
		
		if [ $ok == 1 ]; then
			echo $ok "${1%.*}.$a"
		fi
	)&
	
done
wait
